# .streamlit/secrets.toml
[auth_credentials]
usernames = { "admin" = { "name" = "admin", "password" = "$2b$12$zHu/vovMDoVsiSYFz9Q4zOindy2do7P7PusWvAHHJkn4lmyYqbWHW" } }

[auth_cookie]
name = "moje_ciasteczko_sesji"
key = "jakis_bardzo_dlugi_losowy_klucz_123"
expiry_days = 1





#[credentials]
#user_name = "admin"
#password = "1234"
#
#api_key = "12345-abcde"
#
#[database]
#user = "admin"
#port = 5432
